CLUSTAL multiple sequence alignment by MUSCLE (3.8)


GZ_6_spliced         ACTCGACTTTGTGTGAGGAGAAAATTTCTACACGAGATTTGTCGACACGGCAAATAGATA
Bgt_DR1_spliced      ACTCGACTTTGTGTGAGGAGAAAATTTCTACACGAGATTTGTCGACACGGCAAATAGATA
                     ************************************************************

GZ_6_spliced         ATCAGTGGTCGAATTCTCCATTTACTTTTTCCAGTGCTCTAGTTTACCTTTCGCCAATTA
Bgt_DR1_spliced      ATCAGTGGTCGAATTCTCCATTTACTTTTTCCAGTGCTCTAGTTTACCTTTCGCCAATTA
                     ************************************************************

GZ_6_spliced         TTACAAAATCCCATTCAGCTGCTTGGCTCGGTCGACCCGTGAGTATCGAGACTGTAGACC
Bgt_DR1_spliced      TTACAAAATCCCATTCAGCTGCTTGGCTCGGTCGACCCGTGAGTATCGAGACTGTAGACC
                     ************************************************************

GZ_6_spliced         AATTTTGCTCGTTGGCGTATTTACAGTGAGTTCTAGCAATGGTGAAAGTCGGATTGATTA
Bgt_DR1_spliced      AATTTTGCTCGTTGGCTTATTTACAGTGAGTTCTAGCAATGGTGAAAGTCGGATTGATTA
                     **************** *******************************************

GZ_6_spliced         GAAAAGACTGGCGAGTCAGGTAGGGAATTGTAAGGAGCAAATCACGACGATCCTAGATTC
Bgt_DR1_spliced      GAAAAGACTGGCGAGTCAGGTAGGGAATTGTAAGGAGCAAATCACGACGATCCTAGATTC
                     ************************************************************

GZ_6_spliced         GGGCTCCGTAGGATTGCCAAGTACAATAAAGAGTAAAATGGAAAGAATACCGAAATAATT
Bgt_DR1_spliced      GGGCTCCGTAGGATTGCCAAGTACAATAAAGAGTAAAATGGAAAGAATACCGAAATAATT
                     ************************************************************

GZ_6_spliced         ACGAAATAATACCGAAATAATCTTTCGTGTCACGGAATCTGGCCAATACAACTTTTCGGC
Bgt_DR1_spliced      ACGAAATAATACCGAAATAATCTTTCGTGTCACGGAATCTGGCCAATACAACTTTTCGGC
                     ************************************************************

GZ_6_spliced         CCAATAATAAATCACTCTTTTGGAAATGACTGTCGCCCTAGTCGATTGATGAGCTAATAG
Bgt_DR1_spliced      CCAATAATAAATCACTCTTTTGGAAATGACTGTCGCCCTAGTCGATTGATGAGCTAATAG
                     ************************************************************

GZ_6_spliced         AAACCATTTTAGCTGAGATTAAGTCTTTTATGCGACTGGAGGAAGTGATATTAGATGCTG
Bgt_DR1_spliced      AAACCATTTTAGCTGAGATTAAGTCTTTTATGCGACTGGAGGAAGTGATATTAGATGCTG
                     ************************************************************

GZ_6_spliced         CAAGGATGCTGAAGGATCAATTCATTCTAAATGATTATGTTGATGTATTCAGAAATTGAC
Bgt_DR1_spliced      CAAGGATGCTGAAGGATCAATTCATTCTAAATGATTATGTTGATGTATACAGAAATTGAC
                     ************************************************ ***********

GZ_6_spliced         CCCTTCAAAGAGTTTTGGCAGACTCACAATCTCTGCAGGAAATACATCGTAGATATCCGC
Bgt_DR1_spliced      CTCTCCAAAGAGTATTGGAAGACTCACAATCTCTGCAGGAAATACATCATAGATATCCGC
                     * ** ******** **** ***************************** ***********

GZ_6_spliced         CAACTTCAGCTTCATACTCATCAATAGAACCATCGGTGCGAAAAAAAAGCCCAAACTCAC
Bgt_DR1_spliced      CAACTTCAGCTTGATACTCATCAACAGAACCATCGGTGCGAAAAAAAAGCCCAAACTCAC
                     ************ *********** ***********************************

GZ_6_spliced         CAGCGACAAACATTAGACAGTGTGTGGCCCAATAAATCAGACACCCTACTGTTCTCGTGC
Bgt_DR1_spliced      CAGCGACAAACATTAGATAGTGTGTGACCCAAGAAATCAGACACCCTACTGATCTCGTAC
                     ***************** ******** ***** ****************** ****** *

GZ_6_spliced         AAAATTTAGCTTCGTGCGCCAGCCATCCTCCAAATGAAGTTTCTTGGTGCAGCTTCCACA
Bgt_DR1_spliced      AAAATTTAGCTCCGTGCGCCAGCAATACTCCAAATGAAGTTCCTTGGTGCAGCTTCCACA
                     *********** *********** ** ************** ******************

GZ_6_spliced         GGCGCAATAACTAGCTTTCTGCTCCTGGTGCCTGCTGCTCTCGGAACGCAGGTTTATACA
Bgt_DR1_spliced      GGCGCAATAACCAGCCTTCTGCTCCTGGTGCCTGCTGCTCTCGGAACGCAGGTTTATACA
                     *********** *** ********************************************

GZ_6_spliced         TGTTATAGAAGCCAACCACTTAGCAAGGCTCTAATCGACGATTTAGCAAGATATGCCACT
Bgt_DR1_spliced      TGTTATCGAAGCCAACCACTTAGCAAGGCTCTAATCGACGATTTAGCAAGATATGCCACT
                     ****** *****************************************************

GZ_6_spliced         GCAGATCAAGTGTATCGGAACGATCCAGGGTATGCAGATAGACAGGTGCACAAAACACAT
Bgt_DR1_spliced      GCAGATCAAGTGTATGAGAACGACCCAGGGTACGGAGATAGACAGGTGCACAAGACACAT
                     ***************  ****** ******** * ****************** ******

GZ_6_spliced         CGTTTTTCGAAGAATAAAGACGCAACTGGTTAGATTGAATTCCCAGCTTCTTTGTTGTCA
Bgt_DR1_spliced      CGTTTTTCGAAGAATAAAGACGCAACTGGTTAGATTGAATTCCCAGCTTCTTTGTTGTCA
                     ************************************************************

GZ_6_spliced         CTAACCGTTCTTCTCTAAAACTAGGCCGGGTCGACTACTTGATCCAAATTGTTGGGCCTC
Bgt_DR1_spliced      CTAACCGTTCTTCTCCAAAACTAGGCTCGGTCGACTACTTGATCCAAATTGTTGGGCCTC
                     *************** **********  ********************************

GZ_6_spliced         AAAACACGATCATGGTATTTGAATACTCTTCACATAGTTGGTTGGAGTGTCCTTTGAGCT
Bgt_DR1_spliced      AAAACACGATCATGGTATTTGAATACTCTTCACATAGTTGGTTGGAGTGTCCTTTGAGCT
                     ************************************************************

GZ_6_spliced         AGGGAACGCCAAGATTCAATCGGTAAACGCAATAGGGCGCTATTTGGTATTGGGATACGG
Bgt_DR1_spliced      AGGGAACGCCAAGATTCAATCGGTAAACGCAATAGGGCGCTATTTGGTATTGGGATACGG
                     ************************************************************

GZ_6_spliced         CCAAAACTTCAGATGAAATAGAAGCAGGAAATGTTTCCGATTAAATTTCCAAACAACAAA
Bgt_DR1_spliced      CCAAAACTTCAGATGAAATAGAAGCAGGAAATGTTTCCGATTAAATTTCCAAACAACAAA
                     ************************************************************

GZ_6_spliced         ACTTTCCTTCACCTCTCGAGCTTGCAGATATTTCTATGACCTATCACCCACTATCTAGTG
Bgt_DR1_spliced      ACTTTCCTTCACCTCTCGAGCTTGCAGATATTCCTATGACCTATCACCCACTATCTAGTG
                     ******************************** ***************************

GZ_6_spliced         CTAGATAAATTGATGTAGTTTGTGTCTCAACGTACTTTATATTTGGCAGCTTCTACAGCC
Bgt_DR1_spliced      CTAGATAGATTGATGTAGTTTGTGTCTTAACGTACTTAATATTTGGCAGCTTCTACAGCC
                     ******* ******************* ********* **********************

GZ_6_spliced         CTTGAGGAGTATGCTACTGATCACTAGGCTTTTTGTATAGATTAACATGTTAGTTAGCAC
Bgt_DR1_spliced      CTTGAGGAGTATGCTACCGACCACTAGGCTTTTTCTATAGATTAACATGTTAGTTAGCAA
                     ***************** ** ************* ************************ 

GZ_6_spliced         AATCTATGACTTGCCCGTCACTACTTCTTGCAGTAAGCTCTATTTTGCACATCCTTCGTA
Bgt_DR1_spliced      AATCTATGACTTGCCCGTCACTACTTCTTGCAGTAAGCTCTATTTTGCTCATCCTTCGTA
                     ************************************************ ***********

GZ_6_spliced         GGTCCTCACACGATTAGGATTAGCCATTCATATTCAGAGACTCGGTCTTACAGGCTGGTG
Bgt_DR1_spliced      GGTCCTCACACGATTAGGATTAGTCATTCATATTCAGAGACTCAGTGTTACAGGCTGGTG
                     *********************** ******************* ** *************

GZ_6_spliced         CCTTAAATAGTTATATCCGAAATTTATCAAGTTCATCTATCAGGAAGACTTAGAGTGCAA
Bgt_DR1_spliced      TGTTATTCAGTTATATCCGAAATTTATCCAGTTCATCTATCAGGAAGACTTAGAGTGCAA
                       ***   ******************** *******************************

GZ_6_spliced         ATCCATGCTGGATTAAGGAGTTGTGCAAAGGACAACTC-TGCATAGATTCACGTAACGCG
Bgt_DR1_spliced      ATCCATGCTGGATTAAGGAGTTGGCCAAAGGACAAGTCATGCATAGATTCACGTAACGCG
                     ***********************  ********** ** *********************

GZ_6_spliced         CGGTATTGAGTAAATCTGCAATTAGTCTTCGTAATATTTCCCTCCGTCGTGGGACTATTC
Bgt_DR1_spliced      CGGTATTGAGTAAATCAGAATTTAGTCTTCGTAGTACTTTCCTCCCTTGGGGGACTATTC
                     **************** * * ************ ** ** ***** * * **********

GZ_6_spliced         TCAATTCCAGTTGGTGGTGTCCCCTACGAACCTCCAGCTCTCACTGTCGAGCCTGCAGAG
Bgt_DR1_spliced      TCAACACCTGTCAGCGGTGTCCCCTATGAACCTCCAGCTCTCACTGTAGGGACTGCAGAG
                     ****  ** **  * *********** ******************** * * ********

GZ_6_spliced         CCGAGATTCAGTAAAAAAGTCCTCATTTCCACGAGGATTCCCAATCGCTTTCGCCGTCTG
Bgt_DR1_spliced      GCGAGATTTAGTAACAAAGTCCTCATTTCGACGAGGATTCCCAATCGCTTTCGCGGTCTG
                      ******* ***** ************** ************************ *****

GZ_6_spliced         TATCGTCCTCGTCTCCCAATACATTCTCCTATCACCATTATT
Bgt_DR1_spliced      TATCGTCTTCATCTCTCAACACATTCCCCTATCACCATTATC
                     ******* ** **** *** ****** **************   
